services: 
  database:
    image: mongo:6
    ports: 
      - 27017:27017
    volumes:
      - user_data:/data/db
  
  backend:
    build: ./backend
    container_name: backend
    ports: 
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/todo
    depends_on:
      - database
  
  frontend:
    build: ./frontend/Dtodo
    container_name: frontend
    ports: 
     - "3000:80"
    depends_on:
      - backend

volumes:
  user_data:


